"""Deterministic offline AI client.

Used when `MOCK_OPENAI=true` or no API key is configured. It returns
schema-valid, structurally realistic payloads so the *whole* pipeline - planner,
research, writer, reviewer, document assembly, image generation, patch editing
and PDF export - can be exercised end to end without network access.

The content is obviously placeholder text. It is never used when a real key is
present unless MOCK_OPENAI is explicitly set.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import re
import time
from typing import Any, TypeVar

from pydantic import BaseModel

from app.core.config import Settings, get_settings
from app.core.metrics import CallRecord, current_metrics
from app.services.openai_service import AIClient, ResearchResult, StreamSink

T = TypeVar("T", bound=BaseModel)

_TITLE_RE = re.compile(r"CHAPTER TITLE:\s*(.+)")
_COURSE_RE = re.compile(r"COURSE TITLE:\s*(.+)")
_KIND_RE = re.compile(r"TEMPLATE KIND:\s*(\w+)")
_TOC_RE = re.compile(r"^\s*\d+\.\s*(.+)$", re.MULTILINE)
_BLOCK_ID_RE = re.compile(r"block_[0-9a-f]{6,}")

_LOREM = (
    "This section explains the idea in practical terms and connects it back to the "
    "learner's day-to-day work. Placeholder prose generated by the offline mock "
    "client so that pagination, styling and export can be validated without "
    "calling a language model. "
)


def _line(pattern: re.Pattern[str], text: str, default: str = "") -> str:
    match = pattern.search(text or "")
    return match.group(1).strip() if match else default


class MockAIClient(AIClient):
    is_mock = True

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self.calls: list[dict[str, Any]] = []

    # --- shared plumbing --------------------------------------------------
    async def _simulate(self, kind: str, purpose: str) -> float:
        """Optional latency + metrics so concurrency can be measured offline."""
        started = time.perf_counter()
        metrics = current_metrics()
        if metrics:
            metrics.call_started()
        delay = self.settings.mock_latency_ms / 1000
        if delay:
            await asyncio.sleep(delay)
        if metrics:
            metrics.call_finished()
            metrics.record_call(
                CallRecord(
                    kind=kind,
                    purpose=purpose or kind,
                    model="mock",
                    seconds=time.perf_counter() - started,
                )
            )
        return started

    # --- AIClient ---------------------------------------------------------
    async def structured(
        self,
        *,
        schema: type[T],
        system: str,
        user: str,
        model: str | None = None,
        purpose: str = "",
        phase: str = "default",
        max_output_tokens: int | None = None,
        on_delta: StreamSink | None = None,
    ) -> T:
        self.calls.append({"kind": "structured", "schema": schema.__name__, "purpose": purpose})
        await self._simulate("structured", purpose or schema.__name__)
        builder = _BUILDERS.get(schema.__name__)
        payload = builder(user) if builder else {}
        if on_delta is not None:
            # Deliver the same real (deterministic mock) payload in chunks
            # instead of one shot, so the streaming code path is exercised
            # offline too - not fabricated content, just paced delivery of
            # what would be returned anyway.
            on_delta.reset()
            raw = json.dumps(payload, ensure_ascii=False)
            chunk_size = 24
            for start in range(0, len(raw), chunk_size):
                on_delta.append(raw[start : start + chunk_size])
                # A cooperative yield, not a delay (sleep(0) adds no wall-clock
                # time) - without it this loop never gives the event loop a
                # chance to forward each chunk to an SSE subscriber before the
                # whole payload is already done.
                await asyncio.sleep(0)
        return schema.model_validate(payload)

    async def research(
        self,
        *,
        prompt: str,
        deep: bool = False,
        system: str = "",
        schema: type[BaseModel] | None = None,
        phase: str = "research",
    ) -> ResearchResult:
        self.calls.append({"kind": "research", "deep": deep, "structured": schema is not None})
        await self._simulate("research", "research")
        title = _line(_TITLE_RE, prompt, "the chapter topic")
        # Mirror the real client: when a schema is requested the single call can
        # return the structured payload directly.
        payload = None
        if schema is not None and self.settings.single_call_research:
            builder = _BUILDERS.get(schema.__name__)
            if builder:
                payload = builder(prompt)
        return ResearchResult(
            text=(
                f"Mock research notes for '{title}'.\n"
                "- Definition, mechanism and typical use cases.\n"
                "- Two illustrative examples and one documented case.\n"
                "- Frequent mistakes and current best practice.\n"
            ),
            citations=[{"title": "Mock reference", "url": "https://example.com/mock"}],
            model="mock",
            mode="mock",
            structured=payload,
        )

    async def image(
        self, *, prompt: str, size: str | None = None, phase: str = "image"
    ) -> bytes:
        self.calls.append({"kind": "image"})
        await self._simulate("image", "image")
        return _placeholder_png(prompt, size or self.settings.image_size)


# ---------------------------------------------------------------------------
# payload builders (keyed by schema class name)
# ---------------------------------------------------------------------------


def _planner_output(user: str) -> dict[str, Any]:
    course = _line(_COURSE_RE, user, "Untitled Course")
    titles = _TOC_RE.findall(user) or ["Chapter One", "Chapter Two"]
    chapters = []
    for index, title in enumerate(titles, start=1):
        chapters.append(
            {
                "id": f"chapter_{index}",
                "title": title,
                "order": index,
                "objective": f"Understand and apply the core ideas of {title}.",
                "summary": f"An overview of {title} for the stated audience.",
                "sections": [
                    {
                        "title": "Core ideas",
                        "summary": f"The essentials of {title}.",
                        "key_points": ["Definition", "Mechanism", "Application"],
                    },
                    {
                        "title": "In practice",
                        "summary": "How this shows up in real work.",
                        "key_points": ["Worked example", "Pitfalls"],
                    },
                ],
                "required_blocks": ["heading", "paragraph", "summary", "quiz"],
                "optional_blocks": ["image", "table", "tip"],
                "key_concepts": [f"{title} fundamentals", "Practical trade-offs"],
                "prerequisites": [] if index == 1 else [titles[index - 2]],
                "research_questions": [
                    f"What is {title} and why does it matter?",
                    f"What mistakes do people make with {title}?",
                ],
                "estimated_words": 1400,
                "difficulty": "beginner" if index == 1 else "intermediate",
            }
        )
    return {
        "course_summary": f"A practical course covering {course}.",
        "learning_objectives": [
            f"Explain the core concepts behind {course}.",
            "Apply the material to a realistic scenario.",
            "Avoid the most common mistakes.",
        ],
        "prerequisites": ["Curiosity", "Basic familiarity with the subject area"],
        "tone": "clear, practical, encouraging",
        "chapters": chapters,
        "critique": {
            "missing_concepts": ["A short glossary chapter could help beginners"],
            "duplicate_topics": [],
            "ordering_issues": [],
            "learning_progression_notes": (
                "Progression looks reasonable: foundations first, application later."
            ),
            "suggested_toc": titles,
        },
    }


def _improve_toc(user: str) -> dict[str, Any]:
    titles = _TOC_RE.findall(user) or ["Introduction"]
    suggested = [{"title": t, "sections": [], "notes": ""} for t in titles]
    suggested.append(
        {
            "title": "Putting It All Together",
            "sections": ["Capstone walkthrough"],
            "notes": "Added by the mock planner",
        }
    )
    return {
        "suggested_toc": suggested,
        "changes": [
            {
                "action": "add",
                "target": "",
                "proposed": "Putting It All Together",
                "reason": "The course ends without a chapter that integrates the material.",
            }
        ],
        "reasoning": (
            "The existing order is sound. One integrative closing chapter would "
            "consolidate the learning."
        ),
        "missing_concepts": ["An integrative capstone"],
        "duplicate_topics": [],
    }


def _research_payload(user: str) -> dict[str, Any]:
    title = _line(_TITLE_RE, user, "the topic")
    return {
        "overview": f"{title} explained at a level suitable for the stated audience.",
        "definitions": [
            {"term": title, "definition": f"A working definition of {title}."},
            {"term": "Trade-off", "definition": "A cost accepted in exchange for a benefit."},
        ],
        "core_concepts": ["Foundations", "Mechanism", "Applications", "Limitations"],
        "examples": [
            {
                "title": "Worked example",
                "description": f"A small, concrete illustration of {title}.",
                "why_it_matters": "It shows the mechanism without extra complexity.",
            }
        ],
        "real_world_examples": [
            {
                "title": "Industry usage",
                "description": f"How teams commonly apply {title} in production.",
                "why_it_matters": "Grounds the theory in practice.",
            }
        ],
        "case_studies": [
            {
                "title": "A team adopts the approach",
                "context": "A mid-sized team with a recurring quality problem.",
                "challenge": "Inconsistent results and slow feedback.",
                "approach": f"They introduced {title} incrementally.",
                "outcome": "Fewer defects and faster iteration.",
                "lessons": ["Start small", "Measure before and after"],
            }
        ],
        "important_facts": [
            {
                "statement": f"{title} is widely used in modern practice.",
                "source": "Mock reference",
                "confidence": "medium",
            }
        ],
        "statistics": [],
        "common_mistakes": [
            "Skipping the fundamentals and copying patterns blindly.",
            "Optimising before measuring.",
        ],
        "best_practices": [
            "Introduce the change incrementally.",
            "Document assumptions and revisit them.",
        ],
        "references": [{"title": "Mock reference", "url": "https://example.com/mock", "note": ""}],
        "faq": [
            {
                "question": f"When should I not use {title}?",
                "answer": "When the problem is simpler than the solution.",
            }
        ],
        "visual_opportunities": [
            {
                "purpose": f"Show how {title} fits together",
                "description": "A labelled diagram of the main components and their flow.",
                "suggested_prompt": (
                    f"Clean flat vector diagram explaining {title}, labelled boxes and arrows, "
                    "light background, minimal text"
                ),
            }
        ],
        "exercise_ideas": [
            {
                "title": "Apply it yourself",
                "description": f"Use {title} on a small problem of your own.",
                "difficulty": "medium",
            }
        ],
        "quiz_ideas": [
            {
                "question": f"What problem does {title} solve?",
                "answer": "It addresses the core difficulty described in the chapter.",
                "difficulty": "easy",
            }
        ],
        "open_questions": ["How does this evolve as the system grows?"],
    }


def _chapter_draft(user: str) -> dict[str, Any]:
    title = _line(_TITLE_RE, user, "Chapter")
    kind = _line(_KIND_RE, user, "technical")
    technical = kind == "technical"

    blocks: list[dict[str, Any]] = [
        {"type": "heading", "text": title, "level": 1, "section_key": "introduction"},
        {
            "type": "paragraph",
            "text": _LOREM * 4,
            "section_key": "introduction",
        },
        {
            "type": "learning_objectives",
            "title": "Learning Objectives",
            "items": [
                f"Explain what {title} is and why it matters.",
                "Describe the mechanism in your own words.",
                "Apply the idea to a realistic situation.",
                "Recognise the two most common mistakes.",
            ],
            "section_key": "learning_objectives",
        },
        {
            "type": "heading",
            "text": "Core Concept",
            "level": 2,
            "section_key": "concept" if technical else "core_concept",
        },
        {
            "type": "paragraph",
            "text": _LOREM * 6,
            "section_key": "concept" if technical else "core_concept",
        },
        {
            "type": "callout",
            "title": "Did you know?",
            "text": "Most teams underestimate how much clarity a shared vocabulary buys them.",
            "variant": "did_you_know",
            "section_key": "concept" if technical else "core_concept",
        },
        {
            "type": "image",
            "image_purpose": f"Explain the structure of {title}",
            "image_prompt": (
                f"Clean flat vector diagram explaining {title}: labelled boxes connected by "
                "arrows, light background, minimal text, no photorealism"
            ),
            "caption": f"Figure: how {title} fits together.",
            "alt_text": f"Diagram of {title}",
            "section_key": "visual_explanation" if technical else "framework",
        },
        {
            "type": "table",
            "caption": "When to use which approach",
            "columns": ["Approach", "Best for", "Watch out for"],
            "rows": [
                {"cells": ["Incremental", "Existing systems", "Slower to show impact"]},
                {"cells": ["Greenfield", "New projects", "Easy to over-engineer"]},
            ],
            "section_key": "how_it_works" if technical else "framework",
        },
    ]

    if technical:
        blocks.append(
            {
                "type": "code",
                "language": "python",
                "caption": "A minimal, runnable illustration",
                "code": (
                    "def score(items: list[float]) -> float:\n"
                    '    """Average the inputs, guarding against an empty list."""\n'
                    "    if not items:\n"
                    "        return 0.0\n"
                    "    return sum(items) / len(items)\n\n\n"
                    'if __name__ == "__main__":\n'
                    "    print(score([0.2, 0.5, 0.9]))\n"
                ),
                "section_key": "code_example",
            }
        )
    else:
        blocks.append(
            {
                "type": "story",
                "title": "A Monday morning problem",
                "text": _LOREM * 3,
                "takeaway": "Structure beats improvisation when the stakes are high.",
                "section_key": "story",
            }
        )
        blocks.append(
            {
                "type": "case_study",
                "title": "A team turns a process around",
                "context": "A regional sales team missing targets three quarters in a row.",
                "challenge": "No shared definition of a qualified lead.",
                "actions": [
                    "Agreed a single qualification checklist",
                    "Reviewed it weekly for six weeks",
                ],
                "outcome": "Conversion improved and forecasting became predictable.",
                "lessons": ["Shared definitions first", "Review cadence matters"],
                "section_key": "case_study",
            }
        )

    blocks.extend(
        [
            {
                "type": "warning",
                "title": "Common Mistake",
                "text": "Jumping to the advanced technique before the basics are reliable.",
                "section_key": "common_mistakes",
            },
            {
                "type": "tip",
                "title": "Pro Tip",
                "text": "Write the success criteria down before you start changing anything.",
                "section_key": "best_practices" if technical else "pro_tips",
            },
            {
                "type": "paragraph",
                "text": _LOREM * 5,
                "section_key": "practical_application",
            },
            {
                "type": "exercise",
                "title": "Exercise",
                "instructions": f"Apply {title} to a small problem you already own.",
                "steps": [
                    "Pick a problem small enough to finish in 30 minutes.",
                    "Write down what success looks like.",
                    "Apply the approach from this chapter.",
                    "Note what surprised you.",
                ],
                "hints": ["Keep the scope tiny", "Measure before you change anything"],
                "expected_outcome": "A short write-up of what changed and why.",
                "difficulty": "medium",
                "section_key": "exercise",
            },
            {
                "type": "quiz",
                "title": "Knowledge Check",
                "questions": [
                    {
                        "question": f"What problem does {title} primarily solve?",
                        "kind": "multiple_choice",
                        "options": [
                            "It removes the need for planning",
                            "It makes the mechanism explicit and repeatable",
                            "It guarantees better performance",
                            "It replaces the need for review",
                        ],
                        "answer": "It makes the mechanism explicit and repeatable",
                        "explanation": "The value comes from making the process explicit.",
                    },
                    {
                        "question": "Measuring before changing anything is optional.",
                        "kind": "true_false",
                        "options": ["True", "False"],
                        "answer": "False",
                        "explanation": "Without a baseline you cannot tell whether it helped.",
                    },
                    {
                        "question": "Name one common mistake covered in this chapter.",
                        "kind": "short_answer",
                        "options": [],
                        "answer": "Skipping the fundamentals; optimising before measuring.",
                        "explanation": "Both were listed under Common Mistakes.",
                    },
                ],
                "section_key": "quiz",
            },
            {
                "type": "summary",
                "title": "Summary",
                "key_takeaways": [
                    f"{title} makes an implicit process explicit.",
                    "Start small and measure before and after.",
                    "The common mistakes are predictable and avoidable.",
                ],
                "next_steps": ["Continue to the next chapter and build on this foundation."],
                "section_key": "summary",
            },
        ]
    )

    return {
        "chapter_title": title,
        "blocks": blocks,
        "chapter_summary": (
            f"{title}: defined the concept, walked through the mechanism with an example, "
            "covered common mistakes and best practice, then applied it in an exercise."
        ),
        "words_estimate": 1500,
    }


def _chapter_review(user: str) -> dict[str, Any]:
    return {
        "approved": True,
        "scores": {
            "accuracy": 8.5,
            "clarity": 8.0,
            "structure": 9.0,
            "audience_fit": 8.5,
            "non_repetition": 8.0,
            "logical_flow": 8.5,
            "template_compliance": 9.0,
            "technical_correctness": 8.0,
            "practical_relevance": 8.5,
        },
        "issues": [
            {
                "severity": "minor",
                "category": "clarity",
                "block_index": 1,
                "description": "The opening paragraph could be tightened.",
                "suggestion": "Cut the first sentence and lead with the problem.",
            }
        ],
        "missing_required_blocks": [],
        "dos_violations": [],
        "donts_violations": [],
        "repetition_notes": [],
        "summary": "Solid chapter. Structure and coverage are good; one minor clarity note.",
    }


def _document_patch(user: str) -> dict[str, Any]:
    ids = _BLOCK_ID_RE.findall(user or "")
    target = ids[0] if ids else "block_unknown"
    return {
        "operations": [
            {
                "type": "update_block",
                "block_id": target,
                "content": {
                    "text": (
                        "Simplified explanation produced by the offline mock editor. "
                        "The same idea, expressed in shorter sentences with a concrete "
                        "example the reader can picture immediately."
                    )
                },
            },
            {
                "type": "insert_block",
                "after_block_id": target,
                "block": {
                    "type": "tip",
                    "content": {
                        "title": "Pro Tip",
                        "text": "If you can't explain it in two sentences, split it in two.",
                    },
                    "style": {},
                },
            },
        ],
        "reasoning": "Shortened the selected block and added a reinforcing tip after it.",
        "notes": "Generated by the offline mock client.",
    }


def _planned_summaries(user: str) -> dict[str, Any]:
    ids = re.findall(r"chapter_id:\s*(\S+)\s*\|\s*title:\s*([^|]+)", user or "")
    return {
        "summaries": [
            {
                "chapter_id": chapter_id,
                "summary": (
                    f"{title.strip()}: defines the core ideas, walks through the mechanism "
                    "with an example, then covers the common mistakes."
                ),
            }
            for chapter_id, title in ids
        ]
    }


def _continuity_report(user: str) -> dict[str, Any]:
    return {
        "approved": True,
        "issues": [],
        "summary": "Chapters build on each other without repeating; transitions read cleanly.",
    }


def _block_revision(user: str) -> dict[str, Any]:
    indices = re.findall(r'"index":\s*(\d+)', user or "")
    return {
        "replacements": [
            {
                "index": int(index),
                "block": {
                    "type": "paragraph",
                    "text": (
                        "Revised by the offline mock reviser: the same point, stated more "
                        "plainly and with the reviewer's objection addressed."
                    ),
                },
            }
            for index in indices[:4]
        ],
        "chapter_summary": "Revised chapter: same coverage, clearer wording in the flagged blocks.",
    }


_BUILDERS: dict[str, Any] = {
    "PlannerOutput": _planner_output,
    "PlannedSummaries": _planned_summaries,
    "ContinuityReport": _continuity_report,
    "BlockRevision": _block_revision,
    "ImproveTocResponse": _improve_toc,
    "ResearchPayload": _research_payload,
    "ChapterDraft": _chapter_draft,
    "ChapterReview": _chapter_review,
    "DocumentPatch": _document_patch,
}


# ---------------------------------------------------------------------------
# placeholder image
# ---------------------------------------------------------------------------


def _placeholder_png(prompt: str, size: str) -> bytes:
    """A labelled placeholder so generated PDFs show where images will appear."""
    try:
        width, height = (int(part) for part in size.lower().split("x"))
    except Exception:  # pragma: no cover
        width, height = 1024, 1024

    try:
        from io import BytesIO

        from PIL import Image, ImageDraw

        digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
        tint = tuple(int(digest[i : i + 2], 16) // 4 + 190 for i in (0, 2, 4))
        image = Image.new("RGB", (width, height), tint)
        draw = ImageDraw.Draw(image)
        draw.rectangle([8, 8, width - 8, height - 8], outline=(90, 90, 110), width=4)
        lines = ["MOCK IMAGE", ""]
        words, current = prompt.split(), ""
        for word in words[:40]:
            if len(current) + len(word) > 34:
                lines.append(current)
                current = word
            else:
                current = f"{current} {word}".strip()
        lines.append(current)
        y = height // 2 - 12 * len(lines)
        for line in lines:
            draw.text((32, y), line, fill=(40, 40, 60))
            y += 24
        buffer = BytesIO()
        image.save(buffer, format="PNG")
        return buffer.getvalue()
    except ImportError:  # pragma: no cover - Pillow is a declared dependency
        return _minimal_png()


def _minimal_png() -> bytes:  # pragma: no cover
    import base64

    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg=="
    )
