"""Deterministic offline AI client.

Used when `MOCK_OPENAI=true` or no API key is configured. It returns
schema-valid, structurally realistic payloads so the *whole* pipeline - planner,
research, writer, reviewer, document assembly, image generation, patch editing
and PDF export - can be exercised end to end without network access.

The content is obviously placeholder text. It is never used when a real key is
present unless MOCK_OPENAI is explicitly set.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import re
import time
from typing import Any, Callable, TypeVar

from pydantic import BaseModel

from app.core.config import Settings, get_settings
from app.core.metrics import CallRecord, current_metrics
from app.services.openai_service import AIClient, ResearchResult, StreamSink

T = TypeVar("T", bound=BaseModel)

_TITLE_RE = re.compile(r"CHAPTER TITLE:\s*(.+)")
_COURSE_RE = re.compile(r"COURSE TITLE:\s*(.+)")
_KIND_RE = re.compile(r"TEMPLATE KIND:\s*(\w+)")
_TOC_RE = re.compile(r"^\s*\d+\.\s*(.+)$", re.MULTILINE)
_BLOCK_ID_RE = re.compile(r"block_[0-9a-f]{6,}")

_LOREM = (
    "This section explains the idea in practical terms and connects it back to the "
    "learner's day-to-day work. Placeholder prose generated by the offline mock "
    "client so that pagination, styling and export can be validated without "
    "calling a language model. "
)


def _line(pattern: re.Pattern[str], text: str, default: str = "") -> str:
    match = pattern.search(text or "")
    return match.group(1).strip() if match else default


class MockAIClient(AIClient):
    is_mock = True

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self.calls: list[dict[str, Any]] = []

    # --- shared plumbing --------------------------------------------------
    async def _simulate(self, kind: str, purpose: str) -> float:
        """Optional latency + metrics so concurrency can be measured offline."""
        started = time.perf_counter()
        metrics = current_metrics()
        if metrics:
            metrics.call_started()
        delay = self.settings.mock_latency_ms / 1000
        if delay:
            await asyncio.sleep(delay)
        if metrics:
            metrics.call_finished()
            metrics.record_call(
                CallRecord(
                    kind=kind,
                    purpose=purpose or kind,
                    model="mock",
                    seconds=time.perf_counter() - started,
                )
            )
        return started

    # --- AIClient ---------------------------------------------------------
    async def structured(
        self,
        *,
        schema: type[T],
        system: str,
        user: str,
        model: str | None = None,
        purpose: str = "",
        phase: str = "default",
        max_output_tokens: int | None = None,
        on_delta: StreamSink | None = None,
    ) -> T:
        self.calls.append({"kind": "structured", "schema": schema.__name__, "purpose": purpose})
        await self._simulate("structured", purpose or schema.__name__)
        builder = _BUILDERS.get(schema.__name__)
        payload = builder(user) if builder else {}
        if on_delta is not None:
            # Deliver the same real (deterministic mock) payload in chunks
            # instead of one shot, so the streaming code path is exercised
            # offline too - not fabricated content, just paced delivery of
            # what would be returned anyway.
            on_delta.reset()
            raw = json.dumps(payload, ensure_ascii=False)
            chunk_size = 24
            for start in range(0, len(raw), chunk_size):
                on_delta.append(raw[start : start + chunk_size])
                # A cooperative yield, not a delay (sleep(0) adds no wall-clock
                # time) - without it this loop never gives the event loop a
                # chance to forward each chunk to an SSE subscriber before the
                # whole payload is already done.
                await asyncio.sleep(0)
        return schema.model_validate(payload)

    async def research(
        self,
        *,
        prompt: str,
        deep: bool = False,
        system: str = "",
        schema: type[BaseModel] | None = None,
        phase: str = "research",
        on_event: Callable[[str], None] | None = None,
    ) -> ResearchResult:
        self.calls.append({"kind": "research", "deep": deep, "structured": schema is not None})
        title = _line(_TITLE_RE, prompt, "the chapter topic")
        if on_event is not None:
            # Same "real payload, just paced" convention as structured()'s
            # on_delta chunking above - two lines shaped like genuine
            # web-search-tool progress, derived from the real chapter title,
            # so the SSE wiring is exercised offline without a network call.
            on_event(f"\U0001f50d Searching: {title}")
            await asyncio.sleep(0)
            on_event("\U0001f4c4 Reading: https://example.com/mock-reference")
            await asyncio.sleep(0)
        await self._simulate("research", "research")
        # Mirror the real client: when a schema is requested the single call can
        # return the structured payload directly.
        payload = None
        if schema is not None and self.settings.single_call_research:
            builder = _BUILDERS.get(schema.__name__)
            if builder:
                payload = builder(prompt)
        return ResearchResult(
            text=(
                f"Mock research notes for '{title}'.\n"
                "- Definition, mechanism and typical use cases.\n"
                "- Two illustrative examples and one documented case.\n"
                "- Frequent mistakes and current best practice.\n"
            ),
            citations=[{"title": "Mock reference", "url": "https://example.com/mock"}],
            model="mock",
            mode="mock",
            structured=payload,
        )

    async def image(
        self, *, prompt: str, size: str | None = None, phase: str = "image"
    ) -> bytes:
        self.calls.append({"kind": "image"})
        await self._simulate("image", "image")
        return _placeholder_png(prompt, size or self.settings.image_size)

    async def embed(
        self, *, texts: list[str], model: str | None = None, phase: str = "embedding"
    ) -> list[list[float]]:
        self.calls.append({"kind": "embedding", "count": len(texts)})
        await self._simulate("embedding", "embedding")
        dims = self.settings.embedding_dimensions
        return [_fake_embedding(text, dims) for text in texts]


def _fake_embedding(text: str, dimensions: int) -> list[float]:
    """Deterministic offline stand-in for a real embedding model, using the
    "hashing trick" (feature hashing): every word (and word-bigram) hashes
    into a fixed dimension with a deterministic sign, then the vector is
    normalised. Two texts that share vocabulary land closer together in
    cosine similarity than two that don't - enough to exercise ranking/
    threshold/dedup logic offline - but unlike a real model this has no
    notion of synonymy (e.g. "voltage" vs "EMF" share no tokens), so it
    cannot substitute for a real model when judging true semantic quality.
    """
    words = re.findall(r"[a-z0-9]+", text.lower())
    tokens = list(words) + [f"{a}_{b}" for a, b in zip(words, words[1:])]
    if not tokens:
        tokens = ["__empty__"]
    vector = [0.0] * dimensions
    for token in tokens:
        digest = int(hashlib.sha256(token.encode("utf-8")).hexdigest(), 16)
        index = digest % dimensions
        sign = 1.0 if (digest // dimensions) % 2 == 0 else -1.0
        vector[index] += sign
    norm = sum(v * v for v in vector) ** 0.5 or 1.0
    return [v / norm for v in vector]


# ---------------------------------------------------------------------------
# payload builders (keyed by schema class name)
# ---------------------------------------------------------------------------


def _planner_output(user: str) -> dict[str, Any]:
    course = _line(_COURSE_RE, user, "Untitled Course")
    titles = _TOC_RE.findall(user) or ["Chapter One", "Chapter Two"]
    chapters = []
    for index, title in enumerate(titles, start=1):
        chapters.append(
            {
                "id": f"chapter_{index}",
                "title": title,
                "order": index,
                "objective": f"Understand and apply the core ideas of {title}.",
                "summary": f"An overview of {title} for the stated audience.",
                "sections": [
                    {
                        "title": "Core ideas",
                        "summary": f"The essentials of {title}.",
                        "key_points": ["Definition", "Mechanism", "Application"],
                    },
                    {
                        "title": "In practice",
                        "summary": "How this shows up in real work.",
                        "key_points": ["Worked example", "Pitfalls"],
                    },
                ],
                "required_blocks": ["heading", "paragraph", "summary", "quiz"],
                "optional_blocks": ["image", "table", "tip"],
                "key_concepts": [f"{title} fundamentals", "Practical trade-offs"],
                "prerequisites": [] if index == 1 else [titles[index - 2]],
                "research_questions": [
                    f"What is {title} and why does it matter?",
                    f"What mistakes do people make with {title}?",
                ],
                "estimated_words": 1400,
                "difficulty": "beginner" if index == 1 else "intermediate",
            }
        )
    return {
        "course_summary": f"A practical course covering {course}.",
        "learning_objectives": [
            f"Explain the core concepts behind {course}.",
            "Apply the material to a realistic scenario.",
            "Avoid the most common mistakes.",
        ],
        "prerequisites": ["Curiosity", "Basic familiarity with the subject area"],
        "tone": "clear, practical, encouraging",
        "chapters": chapters,
        "critique": {
            "missing_concepts": ["A short glossary chapter could help beginners"],
            "duplicate_topics": [],
            "ordering_issues": [],
            "learning_progression_notes": (
                "Progression looks reasonable: foundations first, application later."
            ),
            "suggested_toc": titles,
        },
    }


def _improve_toc(user: str) -> dict[str, Any]:
    titles = _TOC_RE.findall(user) or ["Introduction"]
    suggested = [{"title": t, "sections": [], "notes": ""} for t in titles]
    suggested.append(
        {
            "title": "Putting It All Together",
            "sections": ["Capstone walkthrough"],
            "notes": "Added by the mock planner",
        }
    )
    return {
        "suggested_toc": suggested,
        "changes": [
            {
                "action": "add",
                "target": "",
                "proposed": "Putting It All Together",
                "reason": "The course ends without a chapter that integrates the material.",
            }
        ],
        "reasoning": (
            "The existing order is sound. One integrative closing chapter would "
            "consolidate the learning."
        ),
        "missing_concepts": ["An integrative capstone"],
        "duplicate_topics": [],
    }


def _research_payload(user: str) -> dict[str, Any]:
    title = _line(_TITLE_RE, user, "the topic")
    return {
        "overview": f"{title} explained at a level suitable for the stated audience.",
        "definitions": [
            {"term": title, "definition": f"A working definition of {title}."},
            {"term": "Trade-off", "definition": "A cost accepted in exchange for a benefit."},
        ],
        "core_concepts": ["Foundations", "Mechanism", "Applications", "Limitations"],
        "examples": [
            {
                "title": "Worked example",
                "description": f"A small, concrete illustration of {title}.",
                "why_it_matters": "It shows the mechanism without extra complexity.",
            }
        ],
        "real_world_examples": [
            {
                "title": "Industry usage",
                "description": f"How teams commonly apply {title} in production.",
                "why_it_matters": "Grounds the theory in practice.",
            }
        ],
        "case_studies": [
            {
                "title": "A team adopts the approach",
                "context": "A mid-sized team with a recurring quality problem.",
                "challenge": "Inconsistent results and slow feedback.",
                "approach": f"They introduced {title} incrementally.",
                "outcome": "Fewer defects and faster iteration.",
                "lessons": ["Start small", "Measure before and after"],
            }
        ],
        "important_facts": [
            {
                "statement": f"{title} is widely used in modern practice.",
                "source": "Mock reference",
                "confidence": "medium",
            }
        ],
        "statistics": [],
        "common_mistakes": [
            "Skipping the fundamentals and copying patterns blindly.",
            "Optimising before measuring.",
        ],
        "best_practices": [
            "Introduce the change incrementally.",
            "Document assumptions and revisit them.",
        ],
        "references": [{"title": "Mock reference", "url": "https://example.com/mock", "note": ""}],
        "faq": [
            {
                "question": f"When should I not use {title}?",
                "answer": "When the problem is simpler than the solution.",
            }
        ],
        "visual_opportunities": [
            {
                "purpose": f"Show how {title} fits together",
                "description": "A labelled diagram of the main components and their flow.",
                "suggested_prompt": (
                    f"Clean flat vector diagram explaining {title}, labelled boxes and arrows, "
                    "light background, minimal text"
                ),
            }
        ],
        "exercise_ideas": [
            {
                "title": "Apply it yourself",
                "description": f"Use {title} on a small problem of your own.",
                "difficulty": "medium",
            }
        ],
        "quiz_ideas": [
            {
                "question": f"What problem does {title} solve?",
                "answer": "It addresses the core difficulty described in the chapter.",
                "difficulty": "easy",
            }
        ],
        "open_questions": ["How does this evolve as the system grows?"],
    }


def _chapter_draft(user: str) -> dict[str, Any]:
    title = _line(_TITLE_RE, user, "Chapter")
    kind = _line(_KIND_RE, user, "technical")
    technical = kind == "technical"

    blocks: list[dict[str, Any]] = [
        {"type": "heading", "text": title, "level": 1, "section_key": "introduction"},
        {
            "type": "paragraph",
            "text": _LOREM * 4,
            "section_key": "introduction",
        },
        {
            "type": "learning_objectives",
            "title": "Learning Objectives",
            "items": [
                f"Explain what {title} is and why it matters.",
                "Describe the mechanism in your own words.",
                "Apply the idea to a realistic situation.",
                "Recognise the two most common mistakes.",
            ],
            "section_key": "learning_objectives",
        },
        {
            "type": "heading",
            "text": "Core Concept",
            "level": 2,
            "section_key": "concept" if technical else "core_concept",
        },
        {
            "type": "paragraph",
            "text": _LOREM * 6,
            "section_key": "concept" if technical else "core_concept",
        },
        {
            "type": "callout",
            "title": "Did you know?",
            "text": "Most teams underestimate how much clarity a shared vocabulary buys them.",
            "variant": "did_you_know",
            "section_key": "concept" if technical else "core_concept",
        },
        {
            "type": "image",
            "image_purpose": f"Explain the structure of {title}",
            "image_prompt": (
                f"Clean flat vector diagram explaining {title}: labelled boxes connected by "
                "arrows, light background, minimal text, no photorealism"
            ),
            "caption": f"Figure: how {title} fits together.",
            "alt_text": f"Diagram of {title}",
            "section_key": "visual_explanation" if technical else "framework",
        },
        {
            "type": "table",
            "caption": "When to use which approach",
            "columns": ["Approach", "Best for", "Watch out for"],
            "rows": [
                {"cells": ["Incremental", "Existing systems", "Slower to show impact"]},
                {"cells": ["Greenfield", "New projects", "Easy to over-engineer"]},
            ],
            "section_key": "how_it_works" if technical else "framework",
        },
    ]

    if technical:
        blocks.append(
            {
                "type": "code",
                "language": "python",
                "caption": "A minimal, runnable illustration",
                "code": (
                    "def score(items: list[float]) -> float:\n"
                    '    """Average the inputs, guarding against an empty list."""\n'
                    "    if not items:\n"
                    "        return 0.0\n"
                    "    return sum(items) / len(items)\n\n\n"
                    'if __name__ == "__main__":\n'
                    "    print(score([0.2, 0.5, 0.9]))\n"
                ),
                "section_key": "code_example",
            }
        )
    else:
        blocks.append(
            {
                "type": "story",
                "title": "A Monday morning problem",
                "text": _LOREM * 3,
                "takeaway": "Structure beats improvisation when the stakes are high.",
                "section_key": "story",
            }
        )
        blocks.append(
            {
                "type": "case_study",
                "title": "A team turns a process around",
                "context": "A regional sales team missing targets three quarters in a row.",
                "challenge": "No shared definition of a qualified lead.",
                "actions": [
                    "Agreed a single qualification checklist",
                    "Reviewed it weekly for six weeks",
                ],
                "outcome": "Conversion improved and forecasting became predictable.",
                "lessons": ["Shared definitions first", "Review cadence matters"],
                "section_key": "case_study",
            }
        )

    blocks.extend(
        [
            {
                "type": "warning",
                "title": "Common Mistake",
                "text": "Jumping to the advanced technique before the basics are reliable.",
                "section_key": "common_mistakes",
            },
            {
                "type": "tip",
                "title": "Pro Tip",
                "text": "Write the success criteria down before you start changing anything.",
                "section_key": "best_practices" if technical else "pro_tips",
            },
            {
                "type": "paragraph",
                "text": _LOREM * 5,
                "section_key": "practical_application",
            },
            {
                "type": "exercise",
                "title": "Exercise",
                "instructions": f"Apply {title} to a small problem you already own.",
                "steps": [
                    "Pick a problem small enough to finish in 30 minutes.",
                    "Write down what success looks like.",
                    "Apply the approach from this chapter.",
                    "Note what surprised you.",
                ],
                "hints": ["Keep the scope tiny", "Measure before you change anything"],
                "expected_outcome": "A short write-up of what changed and why.",
                "difficulty": "medium",
                "section_key": "exercise",
            },
            {
                "type": "quiz",
                "title": "Knowledge Check",
                "questions": [
                    {
                        "question": f"What problem does {title} primarily solve?",
                        "kind": "multiple_choice",
                        "options": [
                            "It removes the need for planning",
                            "It makes the mechanism explicit and repeatable",
                            "It guarantees better performance",
                            "It replaces the need for review",
                        ],
                        "answer": "It makes the mechanism explicit and repeatable",
                        "explanation": "The value comes from making the process explicit.",
                    },
                    {
                        "question": "Measuring before changing anything is optional.",
                        "kind": "true_false",
                        "options": ["True", "False"],
                        "answer": "False",
                        "explanation": "Without a baseline you cannot tell whether it helped.",
                    },
                    {
                        "question": "Name one common mistake covered in this chapter.",
                        "kind": "short_answer",
                        "options": [],
                        "answer": "Skipping the fundamentals; optimising before measuring.",
                        "explanation": "Both were listed under Common Mistakes.",
                    },
                ],
                "section_key": "quiz",
            },
            {
                "type": "summary",
                "title": "Summary",
                "key_takeaways": [
                    f"{title} makes an implicit process explicit.",
                    "Start small and measure before and after.",
                    "The common mistakes are predictable and avoidable.",
                ],
                "next_steps": ["Continue to the next chapter and build on this foundation."],
                "section_key": "summary",
            },
        ]
    )

    return {
        "chapter_title": title,
        "blocks": blocks,
        "chapter_summary": (
            f"{title}: defined the concept, walked through the mechanism with an example, "
            "covered common mistakes and best practice, then applied it in an exercise."
        ),
        "words_estimate": 1500,
    }


def _chapter_review(user: str) -> dict[str, Any]:
    return {
        "approved": True,
        "scores": {
            "accuracy": 8.5,
            "clarity": 8.0,
            "structure": 9.0,
            "audience_fit": 8.5,
            "non_repetition": 8.0,
            "logical_flow": 8.5,
            "template_compliance": 9.0,
            "technical_correctness": 8.0,
            "practical_relevance": 8.5,
        },
        "issues": [
            {
                "severity": "minor",
                "category": "clarity",
                "block_index": 1,
                "description": "The opening paragraph could be tightened.",
                "suggestion": "Cut the first sentence and lead with the problem.",
            }
        ],
        "missing_required_blocks": [],
        "dos_violations": [],
        "donts_violations": [],
        "repetition_notes": [],
        "summary": "Solid chapter. Structure and coverage are good; one minor clarity note.",
    }


def _document_patch(user: str) -> dict[str, Any]:
    ids = _BLOCK_ID_RE.findall(user or "")
    target = ids[0] if ids else "block_unknown"
    return {
        "operations": [
            {
                "type": "update_block",
                "block_id": target,
                "content": {
                    "text": (
                        "Simplified explanation produced by the offline mock editor. "
                        "The same idea, expressed in shorter sentences with a concrete "
                        "example the reader can picture immediately."
                    )
                },
            },
            {
                "type": "insert_block",
                "after_block_id": target,
                "block": {
                    "type": "tip",
                    "content": {
                        "title": "Pro Tip",
                        "text": "If you can't explain it in two sentences, split it in two.",
                    },
                    "style": {},
                },
            },
        ],
        "reasoning": "Shortened the selected block and added a reinforcing tip after it.",
        "notes": "Generated by the offline mock client.",
    }


def _planned_summaries(user: str) -> dict[str, Any]:
    ids = re.findall(r"chapter_id:\s*(\S+)\s*\|\s*title:\s*([^|]+)", user or "")
    return {
        "summaries": [
            {
                "chapter_id": chapter_id,
                "summary": (
                    f"{title.strip()}: defines the core ideas, walks through the mechanism "
                    "with an example, then covers the common mistakes."
                ),
            }
            for chapter_id, title in ids
        ]
    }


def _continuity_report(user: str) -> dict[str, Any]:
    return {
        "approved": True,
        "issues": [],
        "summary": "Chapters build on each other without repeating; transitions read cleanly.",
    }


def _block_revision(user: str) -> dict[str, Any]:
    indices = re.findall(r'"index":\s*(\d+)', user or "")
    return {
        "replacements": [
            {
                "index": int(index),
                "block": {
                    "type": "paragraph",
                    "text": (
                        "Revised by the offline mock reviser: the same point, stated more "
                        "plainly and with the reviewer's objection addressed."
                    ),
                },
            }
            for index in indices[:4]
        ],
        "chapter_summary": "Revised chapter: same coverage, clearer wording in the flagged blocks.",
    }


def _schematic_spec(title: str, brief: str) -> dict[str, Any]:
    """Offline `schematic` examples spanning physics, chemistry, biology and
    engineering, each matching a registered `app.render.visual_blueprints`
    canonical visual - so the offline test suite exercises the same
    blueprint-defaults / semantic-validation / color-role path the real
    model's output goes through, per domain, with zero external API calls.
    Falls back to a plain, un-typed example (no `visual_type`) for any brief
    that doesn't match a known subject, exercising the generic-schematic
    fallback that must keep working for every visual_type the registry
    doesn't (yet) know about."""
    text = brief.lower()

    if "pulley" in text:
        shapes = [
            {"type": "circle", "id": "pulley", "label": "Pulley Wheel", "role": "primary",
             "size": "medium", "color_role": "structure", "priority": "critical"},
            {"type": "block", "id": "load", "label": "Load", "anchor": "below:pulley",
             "role": "secondary", "size": "medium", "color_role": "secondary", "priority": "critical"},
            {"type": "arrow", "id": "applied_force", "label": "Applied Force", "anchor": "right_of:pulley",
             "target_id": "pulley", "role": "secondary", "size": "small", "color_role": "accent",
             "priority": "important", "rotation": 270},
            {"type": "arrow", "id": "lifting_force", "label": "Lifting Force", "anchor": "left_of:pulley",
             "target_id": "load", "role": "secondary", "size": "small", "color_role": "accent",
             "priority": "important", "rotation": 90},
        ]
        return {
            "kind": "schematic",
            "title": title or "Fixed Pulley",
            "visual_type": "fixed_pulley",
            "learning_objective": "Understand how a fixed pulley redirects an applied force to lift a load.",
            "max_annotations": 5,
            "relationships": [
                {"source": "applied_force", "type": "points_to", "target": "pulley"},
                {"source": "lifting_force", "type": "points_to", "target": "load"},
                {"source": "load", "type": "attached_to", "target": "pulley"},
            ],
            "shapes": shapes,
        }

    if any(word in text for word in ("hydrogen", "oxygen", "water formation", "combustion")):
        shapes = [
            {"type": "block", "id": "hydrogen", "label": "2H₂", "role": "primary", "size": "medium",
             "color_role": "primary", "priority": "critical"},
            {"type": "block", "id": "oxygen", "label": "O₂", "anchor": "orbit:hydrogen",
             "role": "secondary", "size": "medium", "color_role": "secondary", "priority": "critical"},
            {"type": "arrow", "id": "reaction_arrow", "label": "Reaction", "anchor": "right_of:hydrogen",
             "target_id": "water", "role": "secondary", "size": "small", "color_role": "accent",
             "priority": "important"},
            {"type": "block", "id": "water", "label": "2H₂O", "anchor": "orbit:hydrogen",
             "role": "secondary", "size": "medium", "color_role": "fluid", "priority": "critical"},
        ]
        return {
            "kind": "schematic",
            "title": title or "Formation of Water",
            "visual_type": "water_formation",
            "learning_objective": "Understand that hydrogen and oxygen combine in a chemical reaction to form water.",
            "max_annotations": 5,
            "relationships": [
                {"source": "hydrogen", "type": "connected_to", "target": "water"},
                {"source": "oxygen", "type": "connected_to", "target": "water"},
                {"source": "reaction_arrow", "type": "points_to", "target": "water"},
            ],
            "shapes": shapes,
        }

    if "cell" in text and any(word in text for word in ("membrane", "nucleus", "organelle", "cytoplasm")):
        shapes = [
            {"type": "circle", "id": "cell_membrane", "label": "Cell Membrane", "role": "primary",
             "size": "large", "color_role": "structure", "priority": "critical"},
            {"type": "circle", "id": "nucleus", "label": "Nucleus", "anchor": "inside:cell_membrane",
             "role": "secondary", "size": "small", "color_role": "secondary", "priority": "critical"},
            {"type": "label", "id": "mitochondria", "label": "Mitochondria", "anchor": "orbit:cell_membrane",
             "role": "secondary", "color_role": "accent", "priority": "important"},
            {"type": "label", "id": "ribosomes", "label": "Ribosomes", "anchor": "orbit:cell_membrane",
             "role": "secondary", "color_role": "accent", "priority": "important"},
            {"type": "label", "id": "golgi_apparatus", "label": "Golgi Apparatus", "anchor": "orbit:cell_membrane",
             "role": "secondary", "color_role": "fluid", "priority": "optional"},
        ]
        return {
            "kind": "schematic",
            "title": title or "Animal Cell",
            "visual_type": "animal_cell",
            "learning_objective": "Identify the main organelles of an animal cell and how they're arranged within the cell membrane.",
            "max_annotations": 5,
            "relationships": [
                {"source": "nucleus", "type": "inside", "target": "cell_membrane"},
                {"source": "mitochondria", "type": "inside", "target": "cell_membrane"},
            ],
            "shapes": shapes,
        }

    if any(word in text for word in ("ammeter", "induction", "induced current", "galvanometer")):
        rest_shapes = [
            {"type": "coil", "id": "coil", "label": "Coil", "role": "primary", "size": "large",
             "color_role": "accent", "priority": "critical"},
            {"type": "block", "id": "magnet", "label": "Bar Magnet", "sublabel": "N / S",
             "anchor": "left_of:coil", "role": "secondary", "size": "medium", "color_role": "structure",
             "priority": "critical"},
            {"type": "flow", "id": "field_lines", "anchor": "orbit:coil", "target_id": "coil",
             "role": "secondary", "size": "small", "color_role": "magnetic_field", "priority": "important",
             "intensity": 0.3, "label": "Field lines"},
            {"type": "gauge", "id": "ammeter", "sublabel": "Ammeter", "anchor": "below:coil",
             "role": "secondary", "size": "small", "color_role": "secondary", "priority": "critical",
             "rotation": 0},
        ]
        active_shapes = [
            {**shape, "intensity": 0.7} if shape["id"] == "field_lines"
            else {**shape, "rotation": 35} if shape["id"] == "ammeter"
            else shape
            for shape in rest_shapes
        ]
        return {
            "kind": "schematic",
            "title": title or "Electromagnetic Induction",
            "visual_type": "electromagnetic_induction",
            "learning_objective": "Understand how a moving magnet induces a current in a coil, shown by the ammeter's deflection.",
            "max_annotations": 5,
            "relationships": [
                {"source": "magnet", "type": "flows_into", "target": "coil"},
                {"source": "coil", "type": "connected_to", "target": "ammeter"},
            ],
            "states": [
                {"caption": "No current", "shapes": rest_shapes},
                {"caption": "Current flows", "shapes": active_shapes},
            ],
        }

    if any(word in text for word in ("motor", "commutator", "brush", "rotor")):
        shapes = [
            {"type": "coil", "id": "coil", "label": "Coil", "role": "primary", "size": "large",
             "color_role": "accent", "priority": "critical"},
            {"type": "block", "id": "magnet", "label": "Magnet", "sublabel": "N / S", "anchor": "orbit:coil",
             "role": "secondary", "size": "medium", "color_role": "structure", "priority": "critical"},
            {"type": "block", "id": "axle", "label": "Axle", "anchor": "right_of:coil", "role": "secondary",
             "size": "small", "color_role": "structure", "priority": "critical"},
            {"type": "block", "id": "commutator", "label": "Commutator", "anchor": "right_of:axle",
             "role": "secondary", "size": "small", "color_role": "secondary", "priority": "critical"},
            {"type": "block", "id": "brush", "label": "Brush", "anchor": "right_of:commutator",
             "role": "secondary", "size": "small", "color_role": "structure", "priority": "important"},
            {"type": "flow", "id": "magnetic_field", "anchor": "orbit:coil", "target_id": "coil",
             "role": "secondary", "size": "small", "color_role": "magnetic_field", "priority": "important",
             "intensity": 0.6, "label": "Magnetic field"},
        ]
        return {
            "kind": "schematic",
            "title": title or "Simple DC Electric Motor",
            "visual_type": "electric_motor",
            "learning_objective": "Understand how a current-carrying coil in a magnetic field is driven to rotate continuously by the commutator and brushes.",
            "max_annotations": 6,
            "relationships": [
                {"source": "coil", "type": "inside", "target": "magnet"},
                {"source": "axle", "type": "passes_through", "target": "coil"},
                {"source": "coil", "type": "attached_to", "target": "axle"},
                {"source": "axle", "type": "attached_to", "target": "commutator"},
                {"source": "brush", "type": "contacts", "target": "commutator"},
                {"source": "commutator", "type": "connected_to", "target": "coil"},
            ],
            "shapes": shapes,
        }

    # Generic fallback: no visual_type at all - proves an unrecognised/absent
    # visual_type keeps working via the plain semantic schematic path, with
    # no blueprint involved (see app.render.visual_blueprints.get_blueprint).
    shapes = [
        {"type": "block", "id": "source", "role": "primary", "size": "medium", "label": "Source"},
        {
            "type": "flow", "id": "flow", "anchor": "right_of:source", "target_id": "source",
            "priority": "important", "size": "small", "intensity": 0.6, "label": "Effect",
        },
        {
            "type": "gauge", "id": "reading", "anchor": "below:source", "priority": "important",
            "size": "small", "rotation": 30, "sublabel": "Reading",
        },
    ]
    return {
        "kind": "schematic",
        "title": title,
        "learning_objective": f"Understand {title.lower() or 'the concept'}",
        "max_annotations": 5,
        "states": [
            {"caption": "At rest", "shapes": shapes},
            {"caption": "In effect", "shapes": shapes},
        ],
    }


def _java_class_and_object_mock() -> dict[str, Any]:
    return {
        "kind": "concept_experience",
        "concept": "java_class_and_object",
        "domain": "java",
        "representation": "object",
        "title": "Class and Object",
        "learner_level": "beginner",
        "learning_objectives": [
            "Explain that a class is a blueprint/template, not a real thing by itself",
            "Explain that an object is a real instance created from a class",
            "Identify that different objects of the same class can hold different property values",
        ],
        "core_message": "A class is a blueprint; an object is a real thing built from it.",
        "visual_metaphor": "a car blueprint (the Class) and real cars built from it (Objects)",
        "technical_signature": "class Car { color; model; speed; start(); stop(); drive(); }",
        "entities": [
            {
                "id": "car_class", "role": "template", "label": "Car (Class)",
                "properties": {"color": "", "model": "", "speed": ""},
                "actions": ["start()", "stop()", "drive()"],
                "icon": "🏭", "color_role": "primary",
            },
            {
                "id": "car1", "role": "instance", "label": "car1",
                "properties": {"color": "Red", "model": "X1", "speed": "80"},
                "icon": "🚗", "color_role": "accent",
            },
            {
                "id": "car2", "role": "instance", "label": "car2",
                "properties": {"color": "Blue", "model": "X2", "speed": "95"},
                "icon": "🚙", "color_role": "secondary",
            },
            {
                "id": "car3", "role": "instance", "label": "car3",
                "properties": {"color": "Green", "model": "X3", "speed": "70"},
                "icon": "🚘", "color_role": "fluid",
            },
        ],
        "interactions": [
            {"type": "click_class", "target_entity_ids": ["car_class"], "trigger_label": "Click the Class"},
            {"type": "click_object", "target_entity_ids": ["car1", "car2", "car3"], "trigger_label": "click a car"},
            {"type": "create_object", "target_entity_ids": ["car_class"], "trigger_label": "Create Object"},
            {"type": "reset", "target_entity_ids": [], "trigger_label": "Reset"},
        ],
        "validation_criteria": [
            "The Class is visually distinct from every Object",
            "At least two Objects are shown with genuinely different property values",
            "It is visually obvious the Objects were created FROM the Class",
            "No paragraph of body text is required to understand that class=blueprint, object=instance",
        ],
    }


def _python_list_mock() -> dict[str, Any]:
    return {
        "kind": "concept_experience",
        "concept": "python_list",
        "domain": "python",
        "representation": "data_structure",
        "title": "Python List",
        "learner_level": "beginner",
        "learning_objectives": [
            "Explain that a list holds an ordered sequence of items, indexed from 0",
            "Explain that append() adds to the end and pop() removes from the end",
        ],
        "core_message": "A list keeps items in order, and you can add or remove from either end.",
        "technical_signature": "fruits = ['apple', 'banana', 'cherry']",
        "entities": [
            {"id": "item0", "role": "element", "label": "'apple'", "properties": {"index": "0"}, "icon": "🍎", "color_role": "accent"},
            {"id": "item1", "role": "element", "label": "'banana'", "properties": {"index": "1"}, "icon": "🍌", "color_role": "secondary"},
            {"id": "item2", "role": "element", "label": "'cherry'", "properties": {"index": "2"}, "icon": "🍒", "color_role": "fluid"},
        ],
        "interactions": [
            {"type": "push", "target_entity_ids": [], "trigger_label": "append()"},
            {"type": "pop", "target_entity_ids": [], "trigger_label": "pop()"},
            {"type": "reset", "target_entity_ids": [], "trigger_label": "Reset"},
        ],
        "validation_criteria": [
            "Items are shown in their actual list order, indexed from 0",
            "append() and pop() are both demonstrated",
        ],
    }


def _sql_join_mock() -> dict[str, Any]:
    return {
        "kind": "concept_experience",
        "concept": "sql_join",
        "domain": "sql",
        "representation": "relationship",
        "title": "SQL JOIN",
        "learner_level": "beginner",
        "learning_objectives": [
            "Explain that a JOIN combines rows from two tables using a shared key",
            "Identify which column links the two tables together",
        ],
        "core_message": "A JOIN combines matching rows from two tables using a shared key.",
        "technical_signature": "SELECT * FROM orders JOIN customers ON orders.customer_id = customers.id",
        "entities": [
            {"id": "orders", "role": "table", "label": "orders", "properties": {"customer_id": "FK"}, "icon": "🧾", "color_role": "primary"},
            {"id": "customers", "role": "table", "label": "customers", "properties": {"id": "PK"}, "icon": "🗂️", "color_role": "secondary"},
        ],
        "relationships": [
            {"source": "orders", "type": "connected_to", "target": "customers"},
        ],
        "interactions": [
            {"type": "click_object", "target_entity_ids": ["orders", "customers"], "trigger_label": "click a table"},
            {"type": "reset", "target_entity_ids": [], "trigger_label": "Reset"},
        ],
        "validation_criteria": [
            "The two tables are visibly connected, not just two disconnected boxes",
            "The connecting key (customer_id -> id) is identifiable",
        ],
    }


def _tcp_handshake_mock() -> dict[str, Any]:
    return {
        "kind": "concept_experience",
        "concept": "tcp_three_way_handshake",
        "domain": "computer_networks",
        "representation": "sequence",
        "title": "TCP Three-Way Handshake",
        "learner_level": "beginner",
        "learning_objectives": [
            "Understand why the handshake is required before data can be sent",
            "Identify the SYN, SYN-ACK and ACK messages in order",
        ],
        "core_message": "Client and server exchange three messages to establish a reliable connection.",
        "steps": [
            {"id": "syn", "label": "SYN", "description": "Client requests a connection", "order": 0, "icon": "📤", "color_role": "primary"},
            {"id": "syn_ack", "label": "SYN-ACK", "description": "Server acknowledges and replies", "order": 1, "icon": "📥", "color_role": "secondary"},
            {"id": "ack", "label": "ACK", "description": "Client confirms - connection established", "order": 2, "icon": "✅", "color_role": "positive"},
        ],
        "interactions": [
            {"type": "play", "target_entity_ids": [], "trigger_label": "Play"},
            {"type": "next", "target_entity_ids": [], "trigger_label": "Next"},
            {"type": "reset", "target_entity_ids": [], "trigger_label": "Reset"},
        ],
        "validation_criteria": [
            "All three messages (SYN, SYN-ACK, ACK) are shown in the correct order",
            "It is clear the connection is only established after all three steps",
        ],
    }


def _stack_mock() -> dict[str, Any]:
    return {
        "kind": "concept_experience",
        "concept": "stack",
        "domain": "dsa",
        "representation": "data_structure",
        "title": "Stack",
        "learner_level": "beginner",
        "learning_objectives": [
            "Explain that a stack is Last In, First Out (LIFO)",
            "Explain that push adds to the top and pop removes from the top",
        ],
        "core_message": "A stack is Last In, First Out - the last item pushed is the first one popped.",
        "entities": [
            {"id": "plate1", "role": "element", "label": "Plate 1", "properties": {"position": "bottom"}, "icon": "🍽️", "color_role": "structure"},
            {"id": "plate2", "role": "element", "label": "Plate 2", "properties": {"position": "middle"}, "icon": "🍽️", "color_role": "secondary"},
            {"id": "plate3", "role": "element", "label": "Plate 3", "properties": {"position": "top"}, "icon": "🍽️", "color_role": "accent"},
        ],
        "interactions": [
            {"type": "push", "target_entity_ids": [], "trigger_label": "Push"},
            {"type": "pop", "target_entity_ids": [], "trigger_label": "Pop"},
            {"type": "reset", "target_entity_ids": [], "trigger_label": "Reset"},
        ],
        "validation_criteria": [
            "The top of the stack is visually distinguishable from the bottom",
            "Push adds to the top; pop removes from the top - not the bottom",
        ],
    }


def _rag_pipeline_mock() -> dict[str, Any]:
    return {
        "kind": "concept_experience",
        "concept": "rag_pipeline",
        "domain": "ai_llm",
        "representation": "pipeline",
        "title": "RAG (Retrieval-Augmented Generation)",
        "learner_level": "beginner",
        "learning_objectives": [
            "Explain why an LLM retrieves external context before answering",
            "Identify the stages a query passes through in a RAG pipeline",
        ],
        "core_message": "RAG retrieves relevant context first, then asks the LLM to answer using it.",
        "steps": [
            {"id": "query", "label": "Query", "description": "The user asks a question", "order": 0, "icon": "❓", "color_role": "primary"},
            {"id": "embed", "label": "Embed", "description": "The query becomes a vector", "order": 1, "icon": "🔢", "color_role": "secondary"},
            {"id": "retrieve", "label": "Retrieve", "description": "Similar chunks are fetched from a vector DB", "order": 2, "icon": "📚", "color_role": "accent"},
            {"id": "generate", "label": "Generate", "description": "The LLM answers using the retrieved context", "order": 3, "icon": "✨", "color_role": "positive"},
        ],
        "interactions": [
            {"type": "play", "target_entity_ids": [], "trigger_label": "Play"},
            {"type": "next", "target_entity_ids": [], "trigger_label": "Next"},
            {"type": "reset", "target_entity_ids": [], "trigger_label": "Reset"},
        ],
        "validation_criteria": [
            "All four stages (query, embed, retrieve, generate) are shown in order",
            "It is clear retrieval happens BEFORE generation, not after",
        ],
    }


# Keyword -> mock builder, checked in order against the lower-cased brief -
# mirrors _schematic_spec's existing keyword-detection pattern. Only
# "java_class_and_object" has a registered CONCEPT_BLUEPRINT_REGISTRY entry;
# the other five deliberately have none, proving blueprint-free operation
# for real (see the approved plan, section G).
_CONCEPT_EXPERIENCE_KEYWORDS: tuple[tuple[tuple[str, ...], Any], ...] = (
    (("sql", "join"), _sql_join_mock),
    (("tcp", "handshake"), _tcp_handshake_mock),
    (("rag", "retrieval"), _rag_pipeline_mock),
    (("python", "list"), _python_list_mock),
    (("stack",), _stack_mock),
    (("class", "object"), _java_class_and_object_mock),
)


def _concept_experience_spec(title: str, brief: str) -> dict[str, Any]:
    """Offline stand-in for VisualPlanner.plan() - keyword-detects the brief
    across six representative concepts (mirrors `_schematic_spec`'s existing
    physics/bio/chem keyword-detection pattern), so offline tests can prove
    representation-selection genuinely varies by concept without an API key.
    Falls back to the Java Class & Object spec (this POC's one registered
    blueprint) when nothing else matches. `generation_strategy` is left
    blank on the Java entry deliberately, so tests exercise
    concept_visual_blueprints.apply_concept_blueprint_defaults filling it in
    from the registered blueprint, not just echoing back whatever the mock
    already set."""
    text = brief.lower()
    for keywords, builder in _CONCEPT_EXPERIENCE_KEYWORDS:
        if all(keyword in text for keyword in keywords):
            spec = builder()
            spec["title"] = title or spec["title"]
            return spec
    spec = _java_class_and_object_mock()
    spec["title"] = title or spec["title"]
    return spec


def _diagram_spec(user: str) -> dict[str, Any]:
    brief = _line(re.compile(r"VISUAL BRIEF:\s*\n(.+)", re.DOTALL), user, "the concept")
    title = (brief.splitlines() or ["Overview"])[0][:60]
    requested = _line(re.compile(r"REQUESTED DIAGRAM TYPE:\s*(\S+)"), user, "")

    if requested in ("concept_map", "conceptual", "hierarchy"):
        nodes = [
            {"id": "subject", "label": title or "Subject", "detail": "", "level": 0},
            {"id": "part_a", "label": "Component A", "detail": "", "level": 1},
            {"id": "part_b", "label": "Component B", "detail": "", "level": 1},
            {"id": "part_c", "label": "Component C", "detail": "", "level": 1},
        ]
        edges = [
            {"source": "part_a", "target": "subject", "label": "acts on"},
            {"source": "subject", "target": "part_b", "label": "produces"},
            {"source": "part_c", "target": "subject", "label": "relates to"},
        ]
        return {"kind": requested, "title": title, "nodes": nodes, "edges": edges}

    if requested == "comparison":
        nodes = [
            {"id": "option_a", "label": "Option A", "detail": "First alternative"},
            {"id": "option_b", "label": "Option B", "detail": "Second alternative"},
        ]
        return {"kind": "comparison", "title": title, "nodes": nodes, "edges": []}

    if requested == "schematic":
        return _schematic_spec(title, brief)

    if "concept_experience" in user:
        return _concept_experience_spec(title, brief)

    steps = ["Define the problem", "Design the approach", "Apply it", "Review the outcome"]
    nodes = [{"id": f"n{i}", "label": step, "detail": ""} for i, step in enumerate(steps)]
    edges = [
        {"source": f"n{i}", "target": f"n{i + 1}", "label": ""} for i in range(len(steps) - 1)
    ]
    return {"kind": requested or "flow_chart", "title": title, "nodes": nodes, "edges": edges}


def _concept_critique(user: str) -> dict[str, Any]:
    """Offline stand-in for concept_qa's Layer-2 semantic grading call -
    always "everything passed", so an offline test's QA outcome is driven
    entirely by Layer 1 (deterministic) unless a test overrides this builder
    itself to exercise a Layer-2 failure."""
    return {
        "objective_verdicts": [],
        "core_message_delivered": True,
        "core_message_detail": "",
        "criteria_verdicts": [],
        "structure_correct": True,
        "structure_detail": "",
        "interactions_useful": True,
        "interactions_detail": "",
    }


_BUILDERS: dict[str, Any] = {
    "PlannerOutput": _planner_output,
    "PlannedSummaries": _planned_summaries,
    "ContinuityReport": _continuity_report,
    "BlockRevision": _block_revision,
    "ImproveTocResponse": _improve_toc,
    "ResearchPayload": _research_payload,
    "ChapterDraft": _chapter_draft,
    "ChapterReview": _chapter_review,
    "DocumentPatch": _document_patch,
    "DiagramSpec": _diagram_spec,
    "ConceptCritique": _concept_critique,
}


# ---------------------------------------------------------------------------
# placeholder image
# ---------------------------------------------------------------------------


def _placeholder_png(prompt: str, size: str) -> bytes:
    """A labelled placeholder so generated PDFs show where images will appear."""
    try:
        width, height = (int(part) for part in size.lower().split("x"))
    except Exception:  # pragma: no cover
        width, height = 1024, 1024

    try:
        from io import BytesIO

        from PIL import Image, ImageDraw

        digest = hashlib.sha256(prompt.encode("utf-8")).hexdigest()
        tint = tuple(int(digest[i : i + 2], 16) // 4 + 190 for i in (0, 2, 4))
        image = Image.new("RGB", (width, height), tint)
        draw = ImageDraw.Draw(image)
        draw.rectangle([8, 8, width - 8, height - 8], outline=(90, 90, 110), width=4)
        lines = ["MOCK IMAGE", ""]
        words, current = prompt.split(), ""
        for word in words[:40]:
            if len(current) + len(word) > 34:
                lines.append(current)
                current = word
            else:
                current = f"{current} {word}".strip()
        lines.append(current)
        y = height // 2 - 12 * len(lines)
        for line in lines:
            draw.text((32, y), line, fill=(40, 40, 60))
            y += 24
        buffer = BytesIO()
        image.save(buffer, format="PNG")
        return buffer.getvalue()
    except ImportError:  # pragma: no cover - Pillow is a declared dependency
        return _minimal_png()


def _minimal_png() -> bytes:  # pragma: no cover
    import base64

    return base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg=="
    )
