"use client";

import { Sparkles } from "lucide-react";
import { assetUrl } from "@/lib/api/documents";
import { allBlocks } from "@/lib/editor/blocks";
import { useEditor } from "@/lib/editor/store";

/**
 * Images in this MVP come from the backend's image generation, so this panel
 * lists the assets the course already owns and lets the user jump to them.
 */
export function UploadsPanel() {
  const editor = useEditor();
  const doc = editor.document;
  if (!doc) return null;

  const images = allBlocks(doc).filter(
    (block) => block.type === "image" && typeof block.content.path === "string",
  );

  return (
    <div className="flex h-full flex-col">
      <div className="px-3 pb-2 pt-3">
        <p className="text-[12.5px] font-semibold text-ink">Uploads</p>
        <p className="mt-0.5 text-[11px] leading-snug text-ink-400">
          Course images generated by the backend.
        </p>
      </div>

      <div className="subtle-scroll flex-1 space-y-2 overflow-y-auto px-2.5 pb-3">
        {images.length === 0 ? (
          <p className="px-1 text-[11.5px] text-ink-400">No images in this course yet.</p>
        ) : (
          images.map((block) => {
            const source = assetUrl(doc.document_id, block.content.path as string);
            const pageIndex = doc.pages.findIndex((page) =>
              page.blocks.some((candidate) => candidate.id === block.id),
            );
            return (
              <button
                key={block.id}
                type="button"
                onClick={() => {
                  if (pageIndex >= 0) editor.setPage(pageIndex);
                  editor.select([block.id]);
                }}
                className="block w-full overflow-hidden rounded-[7px] border border-line transition-colors hover:border-brand-300"
              >
                {source ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img src={source} alt="" className="h-16 w-full object-cover" />
                ) : null}
              </button>
            );
          })
        )}
      </div>

      <div className="border-t border-line p-2.5">
        <p className="flex items-start gap-1.5 text-[10.5px] leading-snug text-ink-400">
          <Sparkles size={11} className="mt-[1px] shrink-0 text-brand-500" />
          Select an image block and use Replace Image to regenerate it.
        </p>
      </div>
    </div>
  );
}
